# Generated by Django 5.2.1 on 2025-06-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_leave_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='leave_balance',
            field=models.IntegerField(null=True),
        ),
    ]
